export const ENV = {
  SERVER_HOST: process.env.NEXT_PUBLIC_SERVER_HOST,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  API_URL_STRAPI: process.env.NEXT_PUBLIC_API_URL_STRAPI,
  ENDPOINTS: {
    AUTH: {
      REGISTER_INVERSOR: "registro_inversionistas",
      REGISTER_GESTOR: "registro_gestor",
      LOGIN: "loginUsuario",
    },
    USER_ME: "user",
    USER: "users",
    CONTACT: "contact",
    UPDATE: "update",
    PROPERTY_STATUS: "estado-inmueble",
    GENERATE_CODE: "generar-codigo",
    RETREAT: "retiro",
    TRANSACTION: "transaccion",
    SPOUSE_USER: "conyuge-usuario",
    //Datos patrimoniales
    PROPERTY_DATA: "datos-patrimoniales",
    REAL_ESTATE_LIST: "lista-inmuebles",
    CHARGES_LABOR: "cargos-laboral",
    PROPERTY_MANAGER: "gestor-propiedad",
    MANAGERS_VEHICLES: "gestores-vehiculos",
    OTHER_MARRIAGES: "otros-patrimonios",
    COMMERCIAL_REFERENCES: "referencias-comerciales",
    UPDATE_MEDIUM: "update-medio",
    REPRESENTATIVES_LEGAL: "representantes-legal",
    SHAREHOLDER_DATA: "datos-accionistas",
    COMMERCIAL_REFERENCE_DATA: "datos-referencias-comerciales",

    SELECTS: {
      DEPARTMENT: "departamentos",
      PROVINCE: "provincias",
      DISTRICT: "distritos",
      MARITALSTATUS: "estado-civil",
      FAMILY_BURDENS: "cargas-familiar",
      DOCUMENTS: "documentos",
      NATIONALITY: "nacionalidad",
      EMPLOYMENT_STATUS: "estado-laboral",
      YEARS_OLD: "antiguedad",
      PROPERTY_TYPES: "tipos-inmuebles-caracteristicas",
      HALF_INTEREST: "medio-interes",
      ECONOMIC_ACTIVITY: "actividadeconomica",
      PROFESSION: "profesion",
    },
  },
  TOKEN: "token",
};
